{% set name = "opacus" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 6ca3fe46c260608e2a3b1508895319e421aca5484cbb15b45910802fda875bbc
  - url: https://raw.githubusercontent.com/pytorch/opacus/v{{ version }}/dev_requirements.txt
    sha256: 660581ef75367680176e84065f3e149a6a725d2a663b0ac97eb7ab1e458d78e1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - numpy >=1.15
    - python >=3.7
    - scipy >=1.2
    - pytorch >=1.8

test:
  imports:
    - opacus
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://opacus.ai
  summary: Train PyTorch models with Differential Privacy
  dev_url: https://github.com/pytorch/opacus
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ashkan-software
    - ffuuugor
    - karthikprasad
    - alexandresablayrolles
    - sarthakpati
